charts/discord-bot/Chart.yaml
src/commands/index.ts
src/commands/utils/testcommand.ts

chore: test PR workflow with test command

---

package-lock.json
package.json
tsconfig.json

fix: express and app health checker added, match dependencies

---

package-lock.json
package.json
tsconfig.json

fix: modules and tsconfig

---

src/commands/moderation/roleassignment.ts

fix: fixed local export not declared in roleassignment.ts

---

package.json
src/commands/general/testcommand2.ts
src/commands/index.ts
src/commands/utils/testcommand.ts

fix: test command2 and more fixes

---

.github/CHANGELOG.md
.github/COMMANDS.md

chore: Stylized commands layout
Updated the layout of the commands file
N/A
vish#3861

chore: Stylized commands layout

---

.github/CONTRIBUTING.md

docs: fixed typo in contributing doc

docs: fixed typo in contributing doc

---

.github/CHANGELOG.md
src/commands/support/contentmanager.ts
src/commands/utils/help.ts

chore: updated link for .help and fixed typo in .cm
updated the link to the .help command
fixed typo in .cm command
N/A
vish#3861

refactor: updated link for .help and fixed typo in .cm

---

.github/CHANGELOG.md
.github/COMMANDS.md
src/commands/B78XH/version.ts
src/constants.ts

refactor: fixes to .version and download links channel constant added
closes #23 
fixes to .version and download links channel constant added

refactor: fixes to .version and download links channel constant added

---

.github/CHANGELOG.md
.github/CONTRIBUTING.md
src/commands/B78XH/irs.ts

refactor: .irs.B78XH command refactoring, correcting false information
Fixed wrong info on .irs command, clarified knob labeling, and updated contributing to reflect command changes

refactor: .irs.B78XH command refactoring, correcting false information

---

package-lock.json
package.json

chore: updated discord.js package to 13.8.1
Updated discord.js package to 13.8.1 from 13.5.1 most notably this update enables bot functionality via 13.8.0 in the new Voice text channels being added to discord. [Release Notes](https://github.com/discordjs/discord.js/releases/tag/13.8.0)

chore: updated discord.js package to 13.8.1

---

.github/CHANGELOG.md
src/commands/utils/metar.ts
src/constants.ts

fix: fixed metar units
This fixes the metar units sometimes displaying incorrectly, as well as add changes from the previous PR to the changelog that were missed. 
credit to [Peregrine Developments](https://github.com/peregrine-developments) for the fix

fix: fixed metar units

---

.github/CHANGELOG.md
src/commands/moderation/rules.ts
src/constants.ts

fix: rules embed role mention and added roles to constants.ts
N/A

fix: rules embed role mention and added roles to constants.ts

---

package-lock.json
package.json

chore: updated nodemon, got, and moment packages to latest versions for security fix
This fixed previous security vulnerabilities associated with older versions of the packages
n/a

chore: updated nodemon, got, and moment packages to latest versions for security fix

---

.github/CHANGELOG.md
src/commands/memes/cowsay.ts

Fixes a simple issue with cowsay command that can allow a user to abuse it in a way to @everyone

fix: input escape

---

.github/CHANGELOG.md
README.md

fix: fixed broken links in README
Fixes the broken links in readme
n/a

fix: fixed broken links in README

---

.github/CHANGELOG.md
src/commands/B78XH/experimental.ts

refactor: updated exp bug reporting info
Updates info on how to submit a bug report for the B78XH in the .exp command

refactor: updated exp bug reporting info

---

.github/CHANGELOG.md
.github/COMMANDS.md
src/commands/general/website.ts
src/commands/index.ts

feat: added website link command
Adds a command which links to the official Heavy Division website

feat: added website link command

---

.github/CHANGELOG.md
src/index.ts

fear: Error handling for process start
Adds error handling for process start, and interpolates the port. (Credit @NathanInnes, https://github.com/flybywiresim/discord-bot/pull/340)
Port in use case:

fear: Error handling for process start

---

.github/CHANGELOG.md
.github/COMMANDS.md
src/commands/index.ts
src/commands/support/cycle.ts

Added command for nav data warnings regarding cycle
KO#2134

feat: Cycle Warning Command

---

.github/CHANGELOG.md
src/commands/general/when.ts

refactor:when command edit
Edited when command to apply on all of the HeavyDivision feautres 
seojun#0390

refactor: editied when command message

---

.github/CHANGELOG.md
.github/COMMANDS.md
src/commands/general/temporaryCommand.ts
src/commands/general/willithave.ts
src/commands/index.ts

Adds command which answers whether or not the aircraft will have a feature.

feat: add willithave command

---

.github/CHANGELOG.md
.github/COMMANDS.md
src/commands/general/willithave.ts
src/commands/index.ts

Adds command answering the question if the aircraft will have a feature.

feat: willithave

---

.github/CHANGELOG.md
.github/workflows/production.yaml
.github/workflows/staging.yaml

…ater
[chore]: move prod/staging workflow to old-deployment branch, save if needed
Deprecates the deployment workflows, but keeps them in the repo in case they are needed later.
hownowbrowncrow

[chore]: move prod/staging workflow to old-deployment branch, save if needed

---

.github/CHANGELOG.md
README.md
package.json

- Fixes the banner image link where the previous image used a dead discord link
- Remove digital ocean badge
- update semver from 0.1.13 -> 0.1.16
hownowbrowncrow

[docs] update README
